spring:
  application:
    name: sb-ecom
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      port: 6379
      host: redis

  app:
    jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    jwtExpirationMs: 3000000


logging:
  level:
    org:
      springframework: DEBUG
      hibernate:
        SQL: DEBUG
      springframework.security: DEBUG
    com:
      ecommerce:
        project: DEBUG

project:
  image: images/

