spring:
  application:
    name: sb-ecom
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
#
#  app:
#    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
#    jwtExpirationMs: 3000000
#
#
#logging:
#  level:
#    org:
#      springframework: DEBUG
#      hibernate:
#        SQL: DEBUG
#      springframework.security: DEBUG
#    com:
#      ecommerce:
#        project: DEBUG

project:
  image: images/

